### ISSUE TITLE
Donate Page _ input controls do not have ID to associate them with corresponding labels

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#77]
Current Label on radio buttons:
<...label for="_dgx_donate_giving_level_100">
Friend:
<.../label>
<...input aria-labelledby="Friend radio" name="_dgx_donate_amount" checked="" value="100" data-conceal=".other-donation-level" type="radio">
$100
<.../span>

**Sample Code**
<...p>
<...label for="A">Sample:</label> 
<...input type="radio" id="A" name="choice1" />
<.../p>

**Comment by anmolpatel** [comment]
added the ID fields, 
Please re-test

**Comment by HerinHentry** [comment]
[Donate Page_Issues.pdf](https://github.com/mr-bobz/talarts/files/28671/Donate.Page_Issues.pdf)

@anmolpatel : Please find the Automated report from Achecker.ca.
This still has issues.

**Comment by anmolpatel** [comment]
issues fixed, please re-test, the content is all dynamically loaded, so achecker will not pick up on it
@HerinHentry @christosptr

**Comment by HerinHentry** [comment]
This is the NVDA speech view. The amount is not declared for a non sighted user. Please use 
![image](https://cloud.githubusercontent.com/assets/15111528/11015440/42e93aa6-85b3-11e5-88d7-f912269a94b9.png)

<...label for="_dgx_donate_giving_level_100">Friend:<.../label>&nbsp;&nbsp;<...input aria-labelledby="Friend radio" id="_dgx_donate_giving_level_100" name="_dgx_donate_amount" checked="" value="100" data-conceal=".other-donation-level" type="radio">$100<.../span>

Please use the Labels to include the amount in radio buttons.

Same for the Donor informations text boxes & Labels.
![image](https://cloud.githubusercontent.com/assets/15111528/11015457/0628365c-85b4-11e5-9a43-4fa3fb789e21.png)

**The input control needs the id to be "_dgx_donate_donor_first_name" to associate with the label.** Please change all the input controls the same.
<...label for="_dgx_donate_donor_first_name">First Name: *</label><...input aria-required="true" aria-labelledby="Firstname label" name="_dgx_donate_donor_first_name" value="" size="20" data-validate="required" type="text"></div>

This applies to check boxes, input text boxes, combo boxes. 

**Radio buttons have ids associated. It works well. But, only the amount info is missing**

**Donate Button Issue:**
<...input type='image' name='dgx-donate-pay-enabled' value='Donate Now' src='http://talarts.knowbility.org/wp-content/plugins/seamless-donations/images/paypal_btn_donate_lg.gif' />

As per HTML 5.1, Value is not needed for this type of input controls.

_The value content attribute gives the default value of the input element. When the value content attribute is added, set, or removed, if the control's dirty value flag is false, the user agent must set the value of the element to the value of the value content attribute, if there is one, or the empty string otherwise,_

Donate button this is the speech viewer for firefox+nvda --> Removing Value is not going to cause any issues as info is conveyed.
![image](https://cloud.githubusercontent.com/assets/15111528/11015514/9665e51a-85b5-11e5-84e0-0ba529490f61.png)

IE + NVDA says --> This is good too. Remove Value and no loss of data.
![image](https://cloud.githubusercontent.com/assets/15111528/11015521/1038b16a-85b6-11e5-9c15-9455a3e53b30.png)

**Comment by anmolpatel** [comment]
going to try and change the layout for radio button to 
(button) Friend ($100)
(button) Sponsor ($500)
... 

@christosptr @HerinHentry, Please advice is this is a good solution or not!

**Comment by anmolpatel** [comment]
added 
(button) label ($value) 

please re-test

**Comment by HerinHentry** [comment]
@christosptr : Can you please check this? I am also testing this.

**Comment by christosptr** [comment]
I have tested the donation page again

I cannot hear the labels of the text fields. I only hear edit field Also the radio buttons should announce the "I would like to make a donation in the amount of:" We can add this in the aria-label. 

A fieldset should go around the following sections
Donation Information
Tribute Gift
Donor Information
Donor Address

**Comment by HerinHentry** [comment]
@christosptr  #78 mentions about the fieldset. The fieldset has been set in the incorrect place now.
I have done the code inspection and advised on that. Can you please see if I my advise is valid?

**Comment by anmolpatel** [comment]
for the aria label i've changed it to 
I would like to make a donation in the amount of Friend ($100)
@christosptr  is that what you meant  ? :)

**Comment by anmolpatel** [comment]
@christosptr @HerinHentry Please re-test issue with text field, it should be working now

**Comment by HerinHentry** [comment]
@anmolpatel : Text fields are looking okay. But, one small error. Can you please fix? Wrong id & label.
![image](https://cloud.githubusercontent.com/assets/15111528/11055528/3af94820-87cc-11e5-9f52-f8b19d8a6bef.png)

Checkboxes still have issues. I need to check that.
One fieldset does not have legend element. We need to check that as well.

**Comment by anmolpatel** [comment]
fixed the error

**Comment by anmolpatel** [comment]
whats the issue with checkboxes ?

**Comment by HerinHentry** [comment]
@anmolpatel : Labels are not associated with the text boxes still.
Checkboxes if they are single, they do not need any fieldset and legend.
Every Text box & text box should have an id and this needs to be associated with the label with "label for" attribute. Please give it a go. If not we can work together on this tomorrow night.
When you run your report on Achecker, select Options > view by line and this helps with easy decoding.

**Comment by anmolpatel** [comment]
accessibility checker is not picking up on it cause the labels are only added / connected with input type on page ready using jQuery. 
it might be why the aChecker is not picking up on it. Can you Please do a manual check on a one section

**Comment by christosptr** [comment]
closing this as we have #166 issues to have a look when we move to the live site
